import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import InputPost from '../components/InputPost'
import { Posts } from '../components/Posts'
import styles from '../styles/pages/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PickUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.title}>
          PICKUP
        </p>

        <div className={styles.containerInput}>
          <InputPost />
        </div>
        <div className={styles.grid}>
          <Posts
            data={"02/27/2022"}
            autor={"nuggty"}
            post="Learn about Next.js in an interactive course with quizzes!"
          />
          <Posts
            data={"02/27/2022"}
            autor={"nuggty"}
            post="Learn about Next.js in an interactive course with quizzes!"
          />
          <Posts
            data={"02/27/2022"}
            autor={"nuggty"}
            post="Learn about Next.js in an interactive course with quizzes!"
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/nuggty"
          target="_blank"
          rel="noopener noreferrer"
        >
          Feito por
          <span className={styles.logo}>
            @nuggty
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
